### PR TITLE
snprintf函数第二个参数应该为buf_len + 1

### PR DESCRIPTION
**Pull request by haibaoo**
### What problem were solved in this pull request?

Issue Number: close #xxx

Problem:

### CODE REVIEW

**Review by hnwyllmm — APPROVED** [review]

**Comment by hnwyllmm** [comment]
You're right. But you submitted the code with wrong author.

**Comment by haibaoo** [comment]
> You're right. But you submitted the code with wrong author.
should  I change my gitconfig name && commit agin?

**Comment by hnwyllmm** [comment]
> > You're right. But you submitted the code with wrong author.
> > should  I change my gitconfig name && commit agin?

Please refer to  
https://www.bing.com/search?q=git+reset+--amend+reset+author&qs=n&form=QBRE&sp=-1&lq=0&pq=git+reset+--amend+reset+auth&sc=0-28&sk=&cvid=4F3F85037952481E9EAB0F3B612B77DD&ghsh=0&ghacc=0&ghpl=

**Comment by hnwyllmm** [comment]
And you should config your email to your github email first.

**Pull request merged**
